version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/usr/src/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - '8080:80'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
